// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	common: {
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
	}
	nav: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
	}
	errors: {
		/**
		 * P​a​g​e​ ​n​o​t​ ​f​o​u​n​d
		 */
		notFound: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		serverError: string
	}
	home: {
		/**
		 * H​i​,​ ​H​o​w​ ​c​a​n​ ​w​e​ ​h​e​l​p​ ​y​o​u​?
		 */
		greetingLong: string
		list: {
			/**
			 * A​c​c​o​u​n​t​ ​&​ ​a​c​c​e​s​s
			 */
			account: string
			/**
			 * N​e​t​w​o​r​k​ ​&​ ​c​o​n​n​e​c​t​i​v​i​t​y
			 */
			network: string
			/**
			 * S​o​f​t​w​a​r​e​ ​&​ ​a​p​p​l​i​c​a​t​i​o​n​s
			 */
			software: string
			/**
			 * H​a​r​d​w​a​r​e​ ​&​ ​D​e​v​i​c​e​s
			 */
			hardware: string
			/**
			 * S​e​c​u​r​i​t​y​ ​&​ ​P​o​l​i​c​i​e​s
			 */
			security: string
			/**
			 * S​u​p​p​o​r​t​ ​&​ ​S​e​r​v​i​c​e​s
			 */
			support: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	common: {
		/**
		 * Search
		 */
		search: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
	}
	nav: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
	}
	errors: {
		/**
		 * Page not found
		 */
		notFound: () => LocalizedString
		/**
		 * Something went wrong
		 */
		serverError: () => LocalizedString
	}
	home: {
		/**
		 * Hi, How can we help you?
		 */
		greetingLong: () => LocalizedString
		list: {
			/**
			 * Account & access
			 */
			account: () => LocalizedString
			/**
			 * Network & connectivity
			 */
			network: () => LocalizedString
			/**
			 * Software & applications
			 */
			software: () => LocalizedString
			/**
			 * Hardware & Devices
			 */
			hardware: () => LocalizedString
			/**
			 * Security & Policies
			 */
			security: () => LocalizedString
			/**
			 * Support & Services
			 */
			support: () => LocalizedString
		}
	}
}

export type Formatters = {}
